//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""f4706fb2-83e6-4cb1-81c4-07c954c48812"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""9246570e-76fd-449b-99b7-9bc2d4639e15"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""bd0493b3-0dfd-4138-9fac-6b0b62fe8a1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""9612122d-e9d0-4c1a-98c8-91ea3f09155d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""ec4a2de2-7a0c-4a27-ab57-74f04b222540"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""bd2f8770-6ab3-42ca-8de1-a0a4f02165d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseX"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3cdb7da3-e757-4ddd-9226-37dde2471b5b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5457600f-d331-4db8-989f-0bdf663f6325"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""b071cb96-2d50-4fe8-9a14-0ad0033ec546"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnterBlueprintMode"",
                    ""type"": ""Button"",
                    ""id"": ""46ba5238-c4bc-47b6-b3ff-c5f6ed9dbd1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bc649d98-076e-4fd3-b6bf-444259c8ea3d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""687ad9ab-8a76-4985-84c9-c98446e6e303"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""62e4b2b7-b1e3-45e3-acb5-88a8dd27ea46"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e5ac4686-21d9-4cc7-b4d2-f27d4fa27d0e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b36c8d5f-c137-4a02-8c35-8d9af9ee4a74"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""84f540a4-397b-4842-952e-9c362913c9f1"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7dd36a7-fdcf-4ea1-a35a-94b3e99e6be8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b80c8bb7-df52-43af-b84e-98b115ec679c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2b37b3a-49d3-429c-b8b4-9e492edc5cac"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d2ea2f7-3a42-4799-89be-d4ba70be4703"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09400c65-3c57-49e1-9b60-df55cd9e7674"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""521b68f8-7fbe-4a80-8149-b3890aab9b75"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ffe2274-bb62-4a2b-b413-c514817a0821"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6854036d-56bc-4cb1-90ea-50fbe690657d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""996100fa-9df9-4f66-aaf6-c7795c8415b0"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abb60f5a-fcd5-486a-bdde-62d2bdc209c2"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c04dd042-4415-46f2-85a2-e092bac95fac"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""720fa61d-1fde-44e2-aec1-fce0aa5f89ad"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2cd785e-1501-45b8-9380-5554f0b961a0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""383f97a8-6a51-42cc-9356-ea464d370b42"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8ef192a-1df8-4cc1-9413-4afaef9b4e74"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterBlueprintMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BlueprintMap"",
            ""id"": ""0d829615-6232-48b5-b0c3-5fa568ad57bc"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""0eca8e30-582a-47d4-b296-a7d72d75ec38"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseX"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b7b4afaa-a386-4d18-9048-cb88a098b52b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fded425f-32cb-4b58-a30c-1a3e6d4df175"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""9a15861f-2210-48ac-88c8-23b8ae518c6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""5bb77d1f-2a59-407d-9b8d-78ff1d95dfd9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ModifySpeed"",
                    ""type"": ""Button"",
                    ""id"": ""271d10a2-969d-4d5c-b612-e8cadb83a41d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""7aa91d24-6c1d-4f47-a798-a1521b61a1df"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""57ee367c-67f3-4597-9867-ceae4c0b88b2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d5ff21b8-4368-4a41-a376-eb09c184959d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6fd97994-a6e8-4d2c-a4cc-0d195215042f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""35fcc6f5-9c31-44f7-9051-dc1587a9b735"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e0fa2d95-01ac-4ede-8223-98b00a2e58aa"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""878014d3-b9d3-4c8b-a54e-fd31abf3c7dc"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50d0185d-86ec-4d09-8baa-66594759e90c"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab10ff30-1d63-4485-aa29-f9c0ef1c0791"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca3c74da-331c-47d4-bb27-96a333c26d4c"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9390dc3c-96ad-478e-9a0b-39536f470051"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5abeec00-1871-4f4a-938a-80f4d60f2f18"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bb6411f-56ca-4672-904a-938ddf727e20"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d41722e-bb32-45a7-9b23-9d40cd67b048"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7fa0d650-62a4-43f9-963e-4a332627318f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3473c77d-91cd-4e79-a43e-299aeede59f4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4bc8b513-40d9-4e68-aa9b-508988da53dd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4b63b12a-ae8e-4f78-8ff8-c9e2966941b4"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6e7a7b16-f8f3-4caf-a204-be21fea67331"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f22b8457-42f9-4954-8d26-91f039c902d7"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ModifySpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c43b501f-a4c0-4e43-95b2-00f3a65bde49"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ModifySpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d68b29c-7857-44e2-9be4-6aeb6946fe9b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""075995f6-c2bb-48c1-8aa4-f0428b0f8730"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0514f60a-422b-4dd6-a251-bc767358cd9f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""66727bfb-31ba-4d88-91fc-aadbbd43a005"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""98249867-f718-4e13-b9f0-cabe8e0ccf80"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c153bfc5-9f7f-4e32-9939-c918f2ed1d3c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_Move = m_Default.FindAction("Move", throwIfNotFound: true);
        m_Default_Interact = m_Default.FindAction("Interact", throwIfNotFound: true);
        m_Default_Jump = m_Default.FindAction("Jump", throwIfNotFound: true);
        m_Default_Sprint = m_Default.FindAction("Sprint", throwIfNotFound: true);
        m_Default_SwitchCamera = m_Default.FindAction("SwitchCamera", throwIfNotFound: true);
        m_Default_MouseX = m_Default.FindAction("MouseX", throwIfNotFound: true);
        m_Default_MouseY = m_Default.FindAction("MouseY", throwIfNotFound: true);
        m_Default_Cancel = m_Default.FindAction("Cancel", throwIfNotFound: true);
        m_Default_EnterBlueprintMode = m_Default.FindAction("EnterBlueprintMode", throwIfNotFound: true);
        // BlueprintMap
        m_BlueprintMap = asset.FindActionMap("BlueprintMap", throwIfNotFound: true);
        m_BlueprintMap_Move = m_BlueprintMap.FindAction("Move", throwIfNotFound: true);
        m_BlueprintMap_MouseX = m_BlueprintMap.FindAction("MouseX", throwIfNotFound: true);
        m_BlueprintMap_MouseY = m_BlueprintMap.FindAction("MouseY", throwIfNotFound: true);
        m_BlueprintMap_Cancel = m_BlueprintMap.FindAction("Cancel", throwIfNotFound: true);
        m_BlueprintMap_RotateCamera = m_BlueprintMap.FindAction("RotateCamera", throwIfNotFound: true);
        m_BlueprintMap_ModifySpeed = m_BlueprintMap.FindAction("ModifySpeed", throwIfNotFound: true);
        m_BlueprintMap_Zoom = m_BlueprintMap.FindAction("Zoom", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_Move;
    private readonly InputAction m_Default_Interact;
    private readonly InputAction m_Default_Jump;
    private readonly InputAction m_Default_Sprint;
    private readonly InputAction m_Default_SwitchCamera;
    private readonly InputAction m_Default_MouseX;
    private readonly InputAction m_Default_MouseY;
    private readonly InputAction m_Default_Cancel;
    private readonly InputAction m_Default_EnterBlueprintMode;
    public struct DefaultActions
    {
        private @PlayerControls m_Wrapper;
        public DefaultActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Default_Move;
        public InputAction @Interact => m_Wrapper.m_Default_Interact;
        public InputAction @Jump => m_Wrapper.m_Default_Jump;
        public InputAction @Sprint => m_Wrapper.m_Default_Sprint;
        public InputAction @SwitchCamera => m_Wrapper.m_Default_SwitchCamera;
        public InputAction @MouseX => m_Wrapper.m_Default_MouseX;
        public InputAction @MouseY => m_Wrapper.m_Default_MouseY;
        public InputAction @Cancel => m_Wrapper.m_Default_Cancel;
        public InputAction @EnterBlueprintMode => m_Wrapper.m_Default_EnterBlueprintMode;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMove;
                @Interact.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnInteract;
                @Jump.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJump;
                @Sprint.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSprint;
                @SwitchCamera.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSwitchCamera;
                @SwitchCamera.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSwitchCamera;
                @SwitchCamera.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSwitchCamera;
                @MouseX.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMouseX;
                @MouseX.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMouseX;
                @MouseX.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMouseX;
                @MouseY.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMouseY;
                @MouseY.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMouseY;
                @MouseY.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMouseY;
                @Cancel.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnCancel;
                @EnterBlueprintMode.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnEnterBlueprintMode;
                @EnterBlueprintMode.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnEnterBlueprintMode;
                @EnterBlueprintMode.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnEnterBlueprintMode;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @SwitchCamera.started += instance.OnSwitchCamera;
                @SwitchCamera.performed += instance.OnSwitchCamera;
                @SwitchCamera.canceled += instance.OnSwitchCamera;
                @MouseX.started += instance.OnMouseX;
                @MouseX.performed += instance.OnMouseX;
                @MouseX.canceled += instance.OnMouseX;
                @MouseY.started += instance.OnMouseY;
                @MouseY.performed += instance.OnMouseY;
                @MouseY.canceled += instance.OnMouseY;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @EnterBlueprintMode.started += instance.OnEnterBlueprintMode;
                @EnterBlueprintMode.performed += instance.OnEnterBlueprintMode;
                @EnterBlueprintMode.canceled += instance.OnEnterBlueprintMode;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);

    // BlueprintMap
    private readonly InputActionMap m_BlueprintMap;
    private IBlueprintMapActions m_BlueprintMapActionsCallbackInterface;
    private readonly InputAction m_BlueprintMap_Move;
    private readonly InputAction m_BlueprintMap_MouseX;
    private readonly InputAction m_BlueprintMap_MouseY;
    private readonly InputAction m_BlueprintMap_Cancel;
    private readonly InputAction m_BlueprintMap_RotateCamera;
    private readonly InputAction m_BlueprintMap_ModifySpeed;
    private readonly InputAction m_BlueprintMap_Zoom;
    public struct BlueprintMapActions
    {
        private @PlayerControls m_Wrapper;
        public BlueprintMapActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_BlueprintMap_Move;
        public InputAction @MouseX => m_Wrapper.m_BlueprintMap_MouseX;
        public InputAction @MouseY => m_Wrapper.m_BlueprintMap_MouseY;
        public InputAction @Cancel => m_Wrapper.m_BlueprintMap_Cancel;
        public InputAction @RotateCamera => m_Wrapper.m_BlueprintMap_RotateCamera;
        public InputAction @ModifySpeed => m_Wrapper.m_BlueprintMap_ModifySpeed;
        public InputAction @Zoom => m_Wrapper.m_BlueprintMap_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_BlueprintMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BlueprintMapActions set) { return set.Get(); }
        public void SetCallbacks(IBlueprintMapActions instance)
        {
            if (m_Wrapper.m_BlueprintMapActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMove;
                @MouseX.started -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMouseX;
                @MouseX.performed -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMouseX;
                @MouseX.canceled -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMouseX;
                @MouseY.started -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMouseY;
                @MouseY.performed -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMouseY;
                @MouseY.canceled -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnMouseY;
                @Cancel.started -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnCancel;
                @RotateCamera.started -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnRotateCamera;
                @ModifySpeed.started -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnModifySpeed;
                @ModifySpeed.performed -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnModifySpeed;
                @ModifySpeed.canceled -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnModifySpeed;
                @Zoom.started -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_BlueprintMapActionsCallbackInterface.OnZoom;
            }
            m_Wrapper.m_BlueprintMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @MouseX.started += instance.OnMouseX;
                @MouseX.performed += instance.OnMouseX;
                @MouseX.canceled += instance.OnMouseX;
                @MouseY.started += instance.OnMouseY;
                @MouseY.performed += instance.OnMouseY;
                @MouseY.canceled += instance.OnMouseY;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
                @ModifySpeed.started += instance.OnModifySpeed;
                @ModifySpeed.performed += instance.OnModifySpeed;
                @ModifySpeed.canceled += instance.OnModifySpeed;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
            }
        }
    }
    public BlueprintMapActions @BlueprintMap => new BlueprintMapActions(this);
    public interface IDefaultActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnEnterBlueprintMode(InputAction.CallbackContext context);
    }
    public interface IBlueprintMapActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnModifySpeed(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
}
